spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Project
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: VictorMartins
    password: badPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  web:
    cors:
      allowed-origins:
        - "http://localhost:8710"
        - "http://localhost:5173"
        - "http://192.168.178.253:8710"
        - "http://192.168.178.253:5173"
        - "http://msi:5173"
