spring:
  datasource:
    url: jdbc:postgresql://db.nltqgtftdcbzdbgubmoa.supabase.co:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Pass8bad!word@26

    hikari:
      max-lifetime: 180000   # 3 Minuten
      idle-timeout: 120000   # 2 Minuten
      minimum-idle: 1
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: app_todo
    hibernate:
      ddl-auto: update
    show-sql: false
  web:
    cors:
      allowed-origins:
        - "http://localhost:8710"
        - "http://localhost:5173"
        - "http://192.168.178.253:8710"
        - "http://192.168.178.253:5173"
        - "http://msi:5173"
      allowed-methods: "GET,POST, PATCH, PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

